[tool.poetry]
 name = "python-api-tests-2024"
 version = "0.1.0"
 description = ""
 authors = ["alexanderlozovoy <a.litovsky@smartypay.io >"]
 readme = "README.md"

 [tool.poetry.dependencies]
 python = "^3.9"


 [build-system]
 requires = ["poetry-core"]
 build-backend = "poetry.core.masonry.api"